import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import {
  Box,
  Container,
  Paper,
  Typography,
  Button,
  Stack,
  Radio,
  CircularProgress
} from '@mui/material';
import { AutoFixHigh, DriveFileRenameOutline } from '@mui/icons-material';
import { Navbar } from '@/components/ui/navbar';
import { Footer } from '@/components/ui/Footer';
import Stepper from '@/components/ui/Stepper';
import { usePositionsStore } from '@/store/positionsStore';

export default function CriteriaSelection() {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const { currentPosition, getPositionById } = usePositionsStore();
  const [isLoadingPage, setIsLoadingPage] = useState(false);
  const [selection, setSelection] = useState<'full-text' | 'manual' | null>(null);
  const [fullText, setFullText] = useState('');

  const fetchData = async () => {
    setIsLoadingPage(true);
    await getPositionById(id!);
    setIsLoadingPage(false);
  };

  useEffect(() => {
    if (!currentPosition) {
      fetchData();
    }
  }, [id]);

  const handleNext = () => {
    if (selection === 'manual') {
      navigate(`/create-criteria/${id}`);
    } else if (selection === 'full-text') {
      // Do nothing for now as per instructions
    }
  };

  if (isLoadingPage) {
    return (
      <Box display="flex" justifyContent="center" alignItems="center" minHeight="100vh">
        <CircularProgress />
      </Box>
    );
  }

  return (
    <Box sx={{ minHeight: '100vh', backgroundColor: 'background.default' }}>
      <Navbar />
      <Box sx={{ px: { xs: 1.5, md: 6 } }}>
        <Stepper step={1} />
        <Container maxWidth="xl" sx={{ mb: 8 }}>
          <Stack spacing={3.5}>
            {/* Position Display */}
            {currentPosition && (
              <Paper sx={{ borderRadius: '14px', px: { xs: 3, md: 4 }, py: 2, boxShadow: 1 }}>
                <Stack direction="row" alignItems="center" spacing={4}>
                  <Typography sx={{ color: 'text.secondary', fontFamily: 'Montserrat', fontSize: { xs: '1rem', md: '1.25rem' }, fontWeight: 500 }}>
                    Position:
                  </Typography>
                  <Typography sx={{ color: 'primary.dark', fontFamily: 'Montserrat', fontSize: { xs: '1rem', md: '1.25rem' }, fontWeight: 700 }}>
                    {currentPosition.title}
                  </Typography>
                </Stack>
              </Paper>
            )}

            {/* Selection Section */}
            <Paper sx={{ borderRadius: '16px', overflow: 'hidden', boxShadow: 1 }}>
              <Box sx={{ backgroundColor: 'primary.main', px: { xs: 3, md: 4 }, py: 2 }}>
                <Typography variant="h1" sx={{ color: 'white', fontFamily: 'Montserrat', fontSize: { xs: '1rem', md: '1.25rem' }, fontWeight: 700 }}>
                  + Create Criteria
                </Typography>
              </Box>

              <Box sx={{ p: { xs: 3, md: 4 } }}>
                <Stack direction={{ xs: 'column', md: 'row' }} spacing={4} justifyContent="center" sx={{ mb: 4 }}>
                  {/* Full Text Option */}
                  <Paper
                    onClick={() => setSelection('full-text')}
                    sx={{
                      p: 4,
                      borderRadius: '16px',
                      border: selection === 'full-text' ? '2px solid' : '1px solid',
                      borderColor: selection === 'full-text' ? 'primary.main' : 'grey.300',
                      cursor: 'pointer',
                      flex: 1,
                      maxWidth: '400px',
                      display: 'flex',
                      flexDirection: 'column',
                      alignItems: 'center',
                      gap: 2,
                      backgroundColor: selection === 'full-text' ? 'rgba(23, 118, 242, 0.04)' : 'white',
                      transition: 'all 0.3s ease',
                      '&:hover': {
                        borderColor: 'primary.main',
                        backgroundColor: 'rgba(23, 118, 242, 0.02)'
                      }
                    }}
                  >
                    <Stack direction="row" alignItems="center" spacing={1} alignSelf="flex-start">
                      <Radio checked={selection === 'full-text'} />
                      <Typography sx={{ fontFamily: 'Montserrat', fontSize: '0.9rem', color: 'text.secondary' }}>
                        Full Text generated by AI.
                      </Typography>
                    </Stack>
                    <AutoFixHigh sx={{ fontSize: 60, color: 'text.secondary', my: 2 }} />
                  </Paper>

                  {/* Manual Option */}
                  <Paper
                    onClick={() => setSelection('manual')}
                    sx={{
                      p: 4,
                      borderRadius: '16px',
                      border: selection === 'manual' ? '2px solid' : '1px solid',
                      borderColor: selection === 'manual' ? 'primary.main' : 'grey.300',
                      cursor: 'pointer',
                      flex: 1,
                      maxWidth: '400px',
                      display: 'flex',
                      flexDirection: 'column',
                      alignItems: 'center',
                      gap: 2,
                      backgroundColor: selection === 'manual' ? 'rgba(23, 118, 242, 0.04)' : 'white',
                      transition: 'all 0.3s ease',
                      '&:hover': {
                        borderColor: 'primary.main',
                        backgroundColor: 'rgba(23, 118, 242, 0.02)'
                      }
                    }}
                  >
                    <Stack direction="row" alignItems="center" spacing={1} alignSelf="flex-start">
                      <Radio checked={selection === 'manual'} />
                      <Typography sx={{ fontFamily: 'Montserrat', fontSize: '0.9rem', color: 'text.secondary' }}>
                        Add criteria manually.
                      </Typography>
                    </Stack>
                    <DriveFileRenameOutline sx={{ fontSize: 60, color: 'text.secondary', my: 2 }} />
                  </Paper>
                </Stack>

                {/* Conditional Text Area for Full Text */}
                {selection === 'full-text' && (
                  <Box sx={{ maxWidth: '832px', mx: 'auto', mb: 4 }}>
                     <Typography sx={{ mb: 1, fontFamily: 'Montserrat', fontWeight: 600 }}>Enter your criteria text:</Typography>
                      <textarea
                        style={{
                            width: '100%',
                            minHeight: '150px',
                            padding: '16px',
                            borderRadius: '12px',
                            border: '1px solid #C1C1C1',
                            fontFamily: 'Montserrat',
                            fontSize: '1rem',
                            resize: 'vertical',
                            outline: 'none'
                        }}
                        value={fullText}
                        onChange={(e) => setFullText(e.target.value)}
                        placeholder="Paste or type the full criteria text here..."
                      />
                  </Box>
                )}

                {/* Action Buttons */}
                <Stack direction="row" spacing={2} justifyContent="flex-end">
                  <Button
                    onClick={() => navigate('/create-position')}
                    variant="outlined"
                    sx={{
                        px: 3,
                        py: 1,
                        borderRadius: '26px',
                        borderColor: 'grey.400',
                        color: 'primary.dark',
                        fontFamily: 'Montserrat',
                        fontSize: '1rem',
                        fontWeight: 700,
                        textTransform: 'none',
                        '&:hover': { backgroundColor: 'grey.50', borderColor: 'grey.400' },
                    }}
                  >
                    Back
                  </Button>
                  <Button
                    onClick={handleNext}
                    variant="contained"
                    disabled={!selection}
                    sx={{
                        px: 3,
                        py: 1,
                        borderRadius: '26px',
                        backgroundColor: 'primary.main',
                        color: 'white',
                        fontFamily: 'Montserrat',
                        fontSize: '1rem',
                        fontWeight: 700,
                        textTransform: 'none',
                    }}
                  >
                    Next
                  </Button>
                </Stack>
              </Box>
            </Paper>
          </Stack>
        </Container>
      </Box>
      <Footer />
    </Box>
  );
}